name: Windows x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [ { name: MINGW64, arch: x86_64 }, { name: MINGW32, arch: i686 } ]
        compiler: [ { cc: gcc, cpp: g++ }, { cc: clang, cpp: clang++} ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem.name }}
        release: true
        update: false
        path-type: strict
        install: >-
          base-devel git
          mingw-w64-${{ matrix.msystem.name }}-${{ matrix.compiler.cc }}

    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: make
      run: make -j4 CC=${{ matrix.compiler.cc }} CXX=${{ matrix.compiler.cc }} LN=${{ matrix.compiler.cc }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dllbundler-${{ matrix.msystem.name }}-${{ matrix.msystem.arch }}-${{ matrix.compiler.cxx }}
        path: dllbundler.exe
