name: Windows x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem:
          - { sys: mingw64, env: w64-x86_64 }
          - { sys: mingw32, env: w64-i686 }
          - { sys: clang64, env: w64-clang-x86_64 }
          - { sys: clang64, env: w64-clang-i686 }
          - { sys: ucrt64,  env: w64-ucrt-x86_64 }
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }
    defaults:
      run:
        shell: msys2 {0}
    if: "contains(${{ matrix.msystem.sys }}, 'clang') && !contains(${{ matrix.compiler.cc }}, 'gcc')"
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem.sys }}
        release: true
        update: false
        path-type: strict
        install: >-
          base-devel git
          mingw-${{ matrix.msystem.env }}-${{ matrix.compiler.cc }}

    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: make
      run: make -j4 CC=${{ matrix.compiler.cc }}.exe CXX=${{ matrix.compiler.cxx }}.exe LN=${{ matrix.compiler.cxx }}.exe

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dllbundler-${{ matrix.msystem.sys }}-${{ matrix.msystem.env }}-${{ matrix.compiler.cxx }}
        path: dllbundler.exe
