name: Windows x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [MINGW64, MINGW32]
        arch: [x86_64, i686]
        include:
          - cc: gcc
          - cxx: g++
          - cc: clang
          - cxx: clang++
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        release: true
        update: false
        path-type: strict
        install: >-
          base-devel git
          mingw-w64-${{ matrix.arch }}-${{ matrix.cc }}

    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: make
      run: make -j4 CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} LN=${{ matrix.cxx }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dllbundler-${{ matrix.msystem }}-${{ matrix.arch }}-${{ matrix.cxx }}
        path: dllbundler.exe
