name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem:
          - { sys: mingw64, env: w64-x86_64,       compiler: { cc: gcc,   cxx: g++     } }
          - { sys: mingw64, env: w64-x86_64,       compiler: { cc: clang, cxx: clang++ } }
          - { sys: mingw32, env: w64-i686,         compiler: { cc: gcc,   cxx: g++     } }
          - { sys: mingw32, env: w64-i686,         compiler: { cc: clang, cxx: clang++ } }
          - { sys: ucrt64,  env: w64-ucrt-x86_64,  compiler: { cc: gcc,   cxx: g++     } }
          - { sys: ucrt64,  env: w64-ucrt-x86_64,  compiler: { cc: clang, cxx: clang++ } }
          - { sys: clang64, env: w64-clang-x86_64, compiler: { cc: clang, cxx: clang++ } }
          - { sys: clang64, env: w64-clang-i686,   compiler: { cc: clang, cxx: clang++ } }
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem.sys }}
        release: true
        update: false
        path-type: strict
        install: >-
          base-devel git
          mingw-${{ matrix.msystem.env }}-${{ matrix.msystem.compiler.cc }}

    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: make
      run: make -j4 CC=${{ matrix.msystem.compiler.cc }} CXX=${{ matrix.msystem.compiler.cxx }} LN=${{ matrix.msystem.compiler.cxx }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dllbundler-${{ matrix.msystem.sys }}-${{ matrix.msystem.env }}-${{ matrix.msystem.compiler.cxx }}
        path: dllbundler.exe
